### Given an integer array nums, 
return all the triplets [nums[i], nums[j], nums[k]] 
such that 
* i != j, i != k, and j != k
* nums[i] + nums[j] + nums[k] == 0.

In [7]:
def solution(array):
    triplets = []
    for i in range(len(array)):
        found = set()
        for j in range(i+1, len(array)):
            compliment = - (array[i] + array[j])
            if compliment in found:
                continue
            for k in range(j+1, len(array)):
                if array[k] == compliment:
                    triplets.append([array[i], array[j], array[k]])
                    found.add(compliment)
                    break
    return triplets

print(solution([0]*3))
print(solution([0,1,1]))
solution([-1,0,1,2,-1,-4])           

[[0, 0, 0]]
[]


[[-1, 0, 1], [-1, 2, -1], [0, 1, -1]]

Given an array of positive and negative numbers
* arrange them such that all negative integers appear before all the positive integers in the array
* without using any additional data structure like a hash table, arrays, etc. The order of appearance should be maintained.

In [31]:
def segregate_numbers(array):
    pos_idx = None
    for idx, num in enumerate(array):
        if pos_idx is None and num < 0:
            continue
        elif pos_idx is None:
            pos_idx = idx
            continue
        if pos_idx is not None and num < 0:
            array[pos_idx + 1: idx + 1] = array[pos_idx : idx] # shifting positive values 1 step right
            array[pos_idx] = num
            pos_idx += 1
    return array

def recursive_seg_nums(array):
    pos_idx = None
    def change_neg_pos(pos_idx):
        sav = array[pos_idx]
        for i in range(pos_idx + 1, len(array)):
            if array[i] >= 0:
                temp = array[i]
                array[i] = sav
                sav = temp
            else:
                array[pos_idx] = array[i]
                array[i] = sav
                return i
    for idx, num in enumerate(array):
        if pos_idx is not None:
            if change_neg_pos(pos_idx) == len(array) - 1:
                return array
            pos_idx += 1
        elif num >= 0:
            pos_idx = idx
    return array
            
print(recursive_seg_nums([1, 0, -1, -1, 0, 1, -2]), '\n\n' )        
segregate_numbers([1, 0, -1, -1, 0, 1, -2])

[-1, -1, -2, 1, 0, 0, 1] 




[-1, -1, -2, 1, 0, 0, 1]

In [30]:
# Test Cases
print(segregate_numbers([-12, 11, -13, -5, 6, -7, 5, -3, -6]), "\n\n", segregate_numbers([ -12, 11, 13, -5, 6, -7, 5, -3, 8]))

[-12, -13, -5, -7, -3, -6, 11, 6, 5] 

 [-12, -5, -7, -3, 11, 13, 6, 5, 8]


Given an array of N integers and a number K, the task is 
* to find the number of pairs of integers in the array whose sum is equal to K.

In [68]:
def pair_sum_k(array, k):
    pairs = []
    counter = {}
    for num in array:
        counter[num] = counter.get(num, 0) + 1
    found = set()
    for key in counter.keys():
        if key in found:
            continue
        elif k - key == key:
            found.add(key)
            pairs.extend([key, key] for i in range((counter[key] * (counter[key] - 1))//2))
        elif k - key in counter.keys():
            found.add(k - key)
            pairs.extend([[key, k - key] for  i in range(counter[key] * counter[k - key])])
    return pairs

In [71]:
# test case
print(pair_sum_k([1, 5, 7, -1, 3, 3], 6))
print(pair_sum_k([1, 5, 7, -1, 5], 6))

[[1, 5], [7, -1], [3, 3]]
[[1, 5], [1, 5], [7, -1]]


Given an array of `N integers where each value represents the number of chocolates in a packet`. 
Each packet can have a variable number of chocolates. 
There are `m students`, the task is to distribute chocolate packets such that:


    Each student gets one packet.
    The difference between the number of chocolates in the packet with maximum chocolates and the packet with minimum chocolates given to the students is Minimum.


In [84]:
def evenly_distribute(packets, m, get_packets=False):
    # sort the packets
    packets.sort()
    # minimum difference = packets[i: i+m] for min(packets[i + m - 1] - packets[i])
    i = 0
    diff = packets[i + m - 1] - packets[i] # diff for first m packets.sort()
    start = i
    while i < len(packets) - m:
        i += 1
        if diff > packets[i + m - 1] - packets[i]:
            diff = packets[i + m - 1] - packets[i]
            start = i
    if get_packets:
        return diff, packets[start : start + m]
    else:
        return diff

In [85]:
evenly_distribute([7, 3, 2, 4, 9, 12, 56], 3)

2

In [87]:

evenly_distribute([3, 4, 1, 9, 56, 7, 9, 12], 5, True)

(6, [3, 4, 7, 9, 9])

Seven different symbols represent Roman numerals with the following values:
Symbol

Value

* I     1
* V     5
* X     10
* L     50
* C     100
* D     500
* M     1000

Roman numerals are formed by appending the conversions of decimal place values from highest to lowest. Converting a decimal place value into a Roman numeral has the following rules:

    If the value does not start with 4 or 9, select the symbol of the maximal value that can be subtracted from the input, append that symbol to the result, subtract its value, and convert the remainder to a Roman numeral.
    
    If the value starts with 4 or 9 use the subtractive form representing one symbol subtracted from the following symbol, for example, 4 is 1 (I) less than 5 (V): IV and 9 is 1 (I) less than 10 (X): IX. Only the following subtractive forms are used: 4 (IV), 9 (IX), 40 (XL), 90 (XC), 400 (CD) and 900 (CM).
    
    Only powers of 10 (I, X, C, M) can be appended consecutively at most 3 times to represent multiples of 10. You cannot append 5 (V), 50 (L), or 500 (D) multiple times. If you need to append a symbol 4 times use the subtractive form

Given an integer, convert it to a Roman numeral.

In [101]:
def get_roman_numeral(num):
    def convert_to_roman(num):
        if num >= 1000:
            n = num//1000
            remainder = num%1000
            return 'M'*n, remainder
        elif num >= 100:
            n = num//100
            remainder = num%100
            if n == 9:
                return 'CM', remainder
            elif n >= 5:
                return 'D'+('C'* (n - 5)), remainder
            elif n == 4:
                return 'CD', remainder
            else:
                return 'C'*n, remainder
        elif num >= 10:
            n = num//10
            remainder = n%10
            if n == 9:
                return 'XC', remainder
            elif n >= 5:
                return 'L' + ((n - 5) * 'X'), remainder
            elif n == 4:
                return 'XL', remainder
            else:
                return 'X'*n, remainder
        else:
            if num == 9:
                return 'IX', 0
            elif num >= 5:
                return 'V' + ((num - 5) * 'I'), 0
            elif num == 4:
                return 'IV', 0
            else:
                return 'I' * num, 0
    ans = ''
    while num != 0:
        roman_numeral, num = convert_to_roman(num)
        ans += roman_numeral
    return ans
    

In [106]:
get_roman_numeral(3999)

'MMMCMXCIX'

In [141]:
def roman_to_num(romans):
    roman_dict = {'M': 1000, 'CM': 900, 'D': 500,
                 'CD': 400, 'C': 100, 'XC': 90, 'L': 50,
                 'XL': 40, 'X': 10, 'IX': 9, 'V': 5,
                 'IV': 4, 'I': 1}
    search = ''
    ans = 0
    i = 0
    while not ans or search or i < len(romans):
        if len(search) < 2 and i < len(romans):
            search += romans[i]
            i += 1
        else:
            if search in roman_dict:
                ans += roman_dict[search]
                search = ''
            else:
                ans += roman_dict[search[0]]
                search = search[-1]
    return ans

In [142]:
roman_to_num('MMMCMXCIX')

3999

Problem 7: You are given an n x n 2D matrix representing an image, rotate the image by 90 degrees (clockwise). 

You have to rotate the image in-place, which means you have to modify the input 2D matrix directly.
DO NOT allocate another 2D matrix and do the rotation.

In [332]:
n = 5
matrix = [[f'{j}{i}' for i in range(n)] for j in range(n)]

In [333]:
import numpy as np
def rotate_right(matrix):
    """
    Approach : Shifting elements starting from Corner for each sub_matrix/layer in matrix 
    """
    for sub_matrix in range(len(matrix)//2):
        for i in range(sub_matrix, len(matrix) - 1 - sub_matrix):
            # Each subsequent lower layer, the row_index, col index starts from the sub_matrix
            j, r = sub_matrix, i
            sav = matrix[j][r]
            for _ in range(4):
                temp = matrix[j][r]
                matrix[j][r] = sav
                sav = temp
                j, r = r, (len(matrix) - 1 - j)
            matrix[sub_matrix][i] = sav
    return matrix

In [334]:
np.array(matrix)

array([['00', '01', '02', '03', '04'],
       ['10', '11', '12', '13', '14'],
       ['20', '21', '22', '23', '24'],
       ['30', '31', '32', '33', '34'],
       ['40', '41', '42', '43', '44']], dtype='<U2')

In [335]:
np.array(rotate_right(matrix))

array([['40', '30', '20', '10', '00'],
       ['41', '31', '21', '11', '01'],
       ['42', '32', '22', '12', '02'],
       ['43', '33', '23', '13', '03'],
       ['44', '34', '24', '14', '04']], dtype='<U2')

In [345]:
np.array(rotate_right([[5,1,9,11],[2,4,8,10],[13,3,6,7],[15,14,12,16]])) == np.array([[15,13,2,5],[14,3,4,1],[12,6,8,9],[16,7,10,11]])

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [353]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

rotate_right(matrix) == np.array([
    [7, 4, 1],
    [8, 5, 2],
    [9, 6, 3]
])

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [359]:
def rotate_90(matrix):
    for sub_layer in range(len(matrix)//2):
        for i in range(sub_layer, len(matrix) - 1 - sub_layer):
            j, r = sub_layer, i
            sav = matrix[j][r]
            for _ in range(4):
                j, r = r, len(matrix) - 1 - j
                temp = matrix[j][r]
                matrix[j][r] = sav
                sav = temp
    return matrix

In [361]:
n = 5
matrix = [[f'{j}{i}' for i in range(n)] for j in range(n)]
rotate_90(matrix) == np.array([['40', '30', '20', '10', '00'],
       ['41', '31', '21', '11', '01'],
       ['42', '32', '22', '12', '02'],
       ['43', '33', '23', '13', '03'],
       ['44', '34', '24', '14', '04']])

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])